---
- name: Setup Linux Metrics Collection on Multiple Servers
  hosts: slaves
  become: yes
  tasks:

    - name: Install Python, Pip, and Cron
      package:
        name:
          - python3
          - python3-pip
          - cronie  # 'cronie' is the cron package for Amazon Linux & RHEL-based systems
        state: present
        update_cache: yes          

    - name: Install Python dependencies
      pip:
        name:
          - psutil
          - mysql-connector-python
        state: present

    - name: Deploy Python Script for Metrics Collection
      template:
        src: templates/linux_metrics.py.j2 # Path to the python script
        dest: /opt/linux_metrics.py
        owner: ec2-user
        group: ec2-user
        mode: "0755"

    - name: Setup Cron Job for Data Collection
      cron:
        name: "Linux Metrics Collection"
        minute: "*/1"
        job: "/usr/bin/python3 /opt/linux_metrics.py"
        state: present
        user: ec2-user

    - name: Ensure Cron Service Is Running and Restart It
      service:
        name: crond
        state: restarted
        enabled: yes

    # Verify the controller IP address is correctly set on slave machines
    # - name: Debug controller IP
    #   debug:
    #     msg: "Controller IP is {{ controller_ip }}"